### PR TITLE
Fix it.po

### PR DESCRIPTION
**Pull request by sabriunal**
It should be only it.po

### CODE REVIEW

**Comment by carlos157oliveira** [comment]
Good afternoon. Why should it be just "it.po"? I though the "_IT" part specifies the country of the language, in this case italian from Italy.

**Comment by carlos157oliveira** [comment]
I am sorry to bother you, but your example led me to more confusion. While there it is "it.po", there are entries like english which have the followings forms:
- en@shaw.po
- en_CA.po
- en_GB.po
If I am not wasting your time, could you explain further the objectives behind each form and why one would be better than other?

**Comment by sabriunal** [comment]
In English case there are different [spellings](https://www.oxfordinternationalenglish.com/differences-in-british-and-american-spelling/) that makes this naming meaningful. 

In Italian, it's not the same.

**Comment by carlos157oliveira** [comment]
I will trust your italian knowledge.

**Pull request merged**
