### PR TITLE
Appdata and translation related patches

### PR DESCRIPTION
**Pull request by sabriunal**
Please review individually.

### CODE REVIEW

**Comment by carlos157oliveira** [comment]
Good evening. How are you. Thank you for your contributions. Sorry for the delay. I don't know turkish so I would need to trust your translations. I have seen that you added **translatable="no"** to appdata and **vcs-browser** and **translate**. Did you run into something that made these items needed?

**Comment by sabriunal** [comment]
Sorry, I have to add some sources about changes.

```
vcs-browser

    URLs of this type should point to a webpage on which the user can browse the sourcecode. 

translate

    URLs of this type should point to a webpage where users can submit or modify translations of the upstream project.

    Typically this should be a link to the project page in Weblate, Transifex or Zanata, but could also be a link to an upstream-hosted wiki page describing how to send translations upstream. 

```
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url

### data: Mark release descriptions as untranslatable

GNOME automatically excludes release descriptions on Damned Lies (GNOME Translation Platform). It's a good practice to follow the GNOME way.

This can streamline the translation process, allowing translators to focus their efforts on more critical and user-facing aspects of the application.

**Comment by carlos157oliveira** [comment]
I have seen that you have updated **POTFILES.in**. There is a special marker `[type: gettext/glade]` that I had to use for **.ui** files. How did you generate this new list?

**Comment by sabriunal** [comment]
`[type: gettext/glade]` marker seems redundant. I search for `translatable` tag to find translatable ui files.

**Comment by carlos157oliveira** [comment]
The command I was using required `[type: gettext/glade]` to pick up the translation from the **.ui** files, but I don't remember anymore which command I was using lol. Hence I asked you the command you used for generating **POTFILES** and **.pot**. If you could show them to me, it would help my tests. Otherwise, what you've done seems very good to me.

**Comment by sabriunal** [comment]
I documented my find commands in the POTFILES.in

**Comment by carlos157oliveira** [comment]
Good afternoon. Which command did you use to generate "Calculus.pot" ? Was it "intltool-update" or "xgettext" ?

**Comment by sabriunal** [comment]
I have an alias based xgettext

```
pot() {
  local inputf="$1"
  local outputf="$2"
  if [ ! -f "$inputf" ]; then
    echo "Input file not found: $inputf"
    return 1
  fi
  xgettext --files-from="$inputf" --output="$outputf" --from-code=UTF-8 --add-comments --keyword=gettext --keyword=_ --keyword=N_ --keyword=NC_ --keyword=C_:1c,2 "${@:3}"
}
```

**Comment by carlos157oliveira** [comment]
Good afternoon. I checked your work and its all good. For some reason, I have used "intltool-update" and it is not the best practice anymore, "xgettext" evolved enough to not need it. I will merge your contribution if you agree with it. I will probably update the documentation to reflect the current translation process (as to aid myself remember it) and make a small new release afterwards.

**Comment by sabriunal** [comment]
Thanks.

**Pull request merged**
